"""add_performance_foreign_key_indexes

Revision ID: aad9491e464b
Revises: e4f5a6b7c8d9
Create Date: 2026-09-01 22:38:59.573924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aad9491e464b'
down_revision: Union[str, None] = 'e4f5a6b7c8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_admin_export_jobs_admin_user_id'), 'admin_export_jobs', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_job_descriptions_created_by'), 'job_descriptions', ['created_by'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_resume_builder_ats_scores_resume_id'), 'resume_builder_ats_scores', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_builder_bullet_enhancements_experience_id'), 'resume_builder_bullet_enhancements', ['experience_id'], unique=False)
    op.create_index(op.f('ix_resume_builder_documents_user_id'), 'resume_builder_documents', ['user_id'], unique=False)
    op.create_index(op.f('ix_resume_builder_experience_section_id'), 'resume_builder_experience', ['section_id'], unique=False)
    op.create_index(op.f('ix_resume_builder_job_matches_resume_id'), 'resume_builder_job_matches', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_builder_sections_resume_id'), 'resume_builder_sections', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_builder_skills_section_id'), 'resume_builder_skills', ['section_id'], unique=False)
    op.create_index(op.f('ix_resume_builder_versions_resume_id'), 'resume_builder_versions', ['resume_id'], unique=False)
    op.alter_column('resumes', 'advice_status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_resumes_user_id'), 'resumes', ['user_id'], unique=False)
    op.create_index(op.f('ix_saved_jobs_user_id'), 'saved_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_studio_ats_analyses_resume_id'), 'studio_ats_analyses', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_awards_resume_id'), 'studio_awards', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_certifications_resume_id'), 'studio_certifications', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_educations_resume_id'), 'studio_educations', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_experiences_resume_id'), 'studio_experiences', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_job_matches_resume_id'), 'studio_job_matches', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_languages_resume_id'), 'studio_languages', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_projects_resume_id'), 'studio_projects', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_resume_versions_resume_id'), 'studio_resume_versions', ['resume_id'], unique=False)
    op.create_index(op.f('ix_studio_resumes_user_id'), 'studio_resumes', ['user_id'], unique=False)
    op.create_index(op.f('ix_studio_skills_resume_id'), 'studio_skills', ['resume_id'], unique=False)
    op.create_index(op.f('ix_system_alerts_created_by'), 'system_alerts', ['created_by'], unique=False)
    op.create_index(op.f('ix_system_alerts_target_user_id'), 'system_alerts', ['target_user_id'], unique=False)
    op.create_index(op.f('ix_user_feedback_resolved_by'), 'user_feedback', ['resolved_by'], unique=False)
    op.create_index(op.f('ix_user_feedback_user_id'), 'user_feedback', ['user_id'], unique=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'user'::character varying"))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'user'::character varying"))
    op.drop_index(op.f('ix_user_feedback_user_id'), table_name='user_feedback')
    op.drop_index(op.f('ix_user_feedback_resolved_by'), table_name='user_feedback')
    op.drop_index(op.f('ix_system_alerts_target_user_id'), table_name='system_alerts')
    op.drop_index(op.f('ix_system_alerts_created_by'), table_name='system_alerts')
    op.drop_index(op.f('ix_studio_skills_resume_id'), table_name='studio_skills')
    op.drop_index(op.f('ix_studio_resumes_user_id'), table_name='studio_resumes')
    op.drop_index(op.f('ix_studio_resume_versions_resume_id'), table_name='studio_resume_versions')
    op.drop_index(op.f('ix_studio_projects_resume_id'), table_name='studio_projects')
    op.drop_index(op.f('ix_studio_languages_resume_id'), table_name='studio_languages')
    op.drop_index(op.f('ix_studio_job_matches_resume_id'), table_name='studio_job_matches')
    op.drop_index(op.f('ix_studio_experiences_resume_id'), table_name='studio_experiences')
    op.drop_index(op.f('ix_studio_educations_resume_id'), table_name='studio_educations')
    op.drop_index(op.f('ix_studio_certifications_resume_id'), table_name='studio_certifications')
    op.drop_index(op.f('ix_studio_awards_resume_id'), table_name='studio_awards')
    op.drop_index(op.f('ix_studio_ats_analyses_resume_id'), table_name='studio_ats_analyses')
    op.drop_index(op.f('ix_saved_jobs_user_id'), table_name='saved_jobs')
    op.drop_index(op.f('ix_resumes_user_id'), table_name='resumes')
    op.alter_column('resumes', 'advice_status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_resume_builder_versions_resume_id'), table_name='resume_builder_versions')
    op.drop_index(op.f('ix_resume_builder_skills_section_id'), table_name='resume_builder_skills')
    op.drop_index(op.f('ix_resume_builder_sections_resume_id'), table_name='resume_builder_sections')
    op.drop_index(op.f('ix_resume_builder_job_matches_resume_id'), table_name='resume_builder_job_matches')
    op.drop_index(op.f('ix_resume_builder_experience_section_id'), table_name='resume_builder_experience')
    op.drop_index(op.f('ix_resume_builder_documents_user_id'), table_name='resume_builder_documents')
    op.drop_index(op.f('ix_resume_builder_bullet_enhancements_experience_id'), table_name='resume_builder_bullet_enhancements')
    op.drop_index(op.f('ix_resume_builder_ats_scores_resume_id'), table_name='resume_builder_ats_scores')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_job_descriptions_created_by'), table_name='job_descriptions')
    op.drop_index(op.f('ix_admin_export_jobs_admin_user_id'), table_name='admin_export_jobs')
    # ### end Alembic commands ###
